// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaincode.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InstallCCRequest struct {
	CcId                 string   `protobuf:"bytes,1,opt,name=cc_id,json=ccId,proto3" json:"cc_id,omitempty"`
	CcVersion            string   `protobuf:"bytes,2,opt,name=cc_version,json=ccVersion,proto3" json:"cc_version,omitempty"`
	CcPath               string   `protobuf:"bytes,3,opt,name=cc_path,json=ccPath,proto3" json:"cc_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallCCRequest) Reset()         { *m = InstallCCRequest{} }
func (m *InstallCCRequest) String() string { return proto.CompactTextString(m) }
func (*InstallCCRequest) ProtoMessage()    {}
func (*InstallCCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97136ef4b384cc22, []int{0}
}

func (m *InstallCCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallCCRequest.Unmarshal(m, b)
}
func (m *InstallCCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallCCRequest.Marshal(b, m, deterministic)
}
func (m *InstallCCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallCCRequest.Merge(m, src)
}
func (m *InstallCCRequest) XXX_Size() int {
	return xxx_messageInfo_InstallCCRequest.Size(m)
}
func (m *InstallCCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallCCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallCCRequest proto.InternalMessageInfo

func (m *InstallCCRequest) GetCcId() string {
	if m != nil {
		return m.CcId
	}
	return ""
}

func (m *InstallCCRequest) GetCcVersion() string {
	if m != nil {
		return m.CcVersion
	}
	return ""
}

func (m *InstallCCRequest) GetCcPath() string {
	if m != nil {
		return m.CcPath
	}
	return ""
}

type InstantiateCCRequest struct {
	ChannelId            string   `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	CcId                 string   `protobuf:"bytes,2,opt,name=cc_id,json=ccId,proto3" json:"cc_id,omitempty"`
	CcVersion            string   `protobuf:"bytes,3,opt,name=cc_version,json=ccVersion,proto3" json:"cc_version,omitempty"`
	CcPath               string   `protobuf:"bytes,4,opt,name=cc_path,json=ccPath,proto3" json:"cc_path,omitempty"`
	Args                 [][]byte `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstantiateCCRequest) Reset()         { *m = InstantiateCCRequest{} }
func (m *InstantiateCCRequest) String() string { return proto.CompactTextString(m) }
func (*InstantiateCCRequest) ProtoMessage()    {}
func (*InstantiateCCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97136ef4b384cc22, []int{1}
}

func (m *InstantiateCCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstantiateCCRequest.Unmarshal(m, b)
}
func (m *InstantiateCCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstantiateCCRequest.Marshal(b, m, deterministic)
}
func (m *InstantiateCCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstantiateCCRequest.Merge(m, src)
}
func (m *InstantiateCCRequest) XXX_Size() int {
	return xxx_messageInfo_InstantiateCCRequest.Size(m)
}
func (m *InstantiateCCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstantiateCCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstantiateCCRequest proto.InternalMessageInfo

func (m *InstantiateCCRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *InstantiateCCRequest) GetCcId() string {
	if m != nil {
		return m.CcId
	}
	return ""
}

func (m *InstantiateCCRequest) GetCcVersion() string {
	if m != nil {
		return m.CcVersion
	}
	return ""
}

func (m *InstantiateCCRequest) GetCcPath() string {
	if m != nil {
		return m.CcPath
	}
	return ""
}

func (m *InstantiateCCRequest) GetArgs() [][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

type InstantiateCCResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=protos.StatusCode" json:"status,omitempty"`
	TransactionId        string     `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InstantiateCCResponse) Reset()         { *m = InstantiateCCResponse{} }
func (m *InstantiateCCResponse) String() string { return proto.CompactTextString(m) }
func (*InstantiateCCResponse) ProtoMessage()    {}
func (*InstantiateCCResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97136ef4b384cc22, []int{2}
}

func (m *InstantiateCCResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstantiateCCResponse.Unmarshal(m, b)
}
func (m *InstantiateCCResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstantiateCCResponse.Marshal(b, m, deterministic)
}
func (m *InstantiateCCResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstantiateCCResponse.Merge(m, src)
}
func (m *InstantiateCCResponse) XXX_Size() int {
	return xxx_messageInfo_InstantiateCCResponse.Size(m)
}
func (m *InstantiateCCResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstantiateCCResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstantiateCCResponse proto.InternalMessageInfo

func (m *InstantiateCCResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_SUCCESS
}

func (m *InstantiateCCResponse) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func init() {
	proto.RegisterType((*InstallCCRequest)(nil), "protos.InstallCCRequest")
	proto.RegisterType((*InstantiateCCRequest)(nil), "protos.InstantiateCCRequest")
	proto.RegisterType((*InstantiateCCResponse)(nil), "protos.InstantiateCCResponse")
}

func init() { proto.RegisterFile("chaincode.proto", fileDescriptor_97136ef4b384cc22) }

var fileDescriptor_97136ef4b384cc22 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0x19, 0xbf, 0xcc, 0x5e, 0x00, 0x4d, 0xc5, 0xb8, 0x10, 0x49, 0xc8, 0x12, 0x13, 0x62,
	0x02, 0x1a, 0x3c, 0x7b, 0x71, 0xa7, 0x5d, 0x8c, 0x99, 0x89, 0x07, 0x2f, 0x4b, 0x79, 0xad, 0x6c,
	0x0a, 0x2d, 0xb6, 0x85, 0x3f, 0xc5, 0x83, 0x7f, 0xad, 0xb1, 0x05, 0x06, 0x4b, 0xf0, 0xb4, 0xe5,
	0xf3, 0xb6, 0xf7, 0xfd, 0xf4, 0xbd, 0xc2, 0x29, 0x66, 0x34, 0x17, 0x28, 0x19, 0x1f, 0x2f, 0x95,
	0x34, 0x92, 0x34, 0xed, 0x43, 0xf7, 0x5a, 0x28, 0x17, 0x0b, 0x29, 0x1c, 0x0d, 0x53, 0x38, 0x8b,
	0x85, 0x36, 0x74, 0x3e, 0x8f, 0xa2, 0x84, 0x7f, 0xad, 0xb8, 0x36, 0xe4, 0x1c, 0x1a, 0x88, 0x69,
	0xce, 0x02, 0x6f, 0xe0, 0x0d, 0xfd, 0xa4, 0x8e, 0x18, 0x33, 0xd2, 0x07, 0x40, 0x4c, 0xd7, 0x5c,
	0xe9, 0x5c, 0x8a, 0xa0, 0x6a, 0x2b, 0x3e, 0xe2, 0xab, 0x03, 0xe4, 0x12, 0x4e, 0x10, 0xd3, 0x25,
	0x35, 0x59, 0x50, 0xb3, 0xb5, 0x26, 0xe2, 0x33, 0x35, 0x59, 0xf8, 0xed, 0x41, 0xd7, 0x26, 0x08,
	0x93, 0x53, 0xc3, 0x8b, 0x94, 0xbf, 0x86, 0x19, 0x15, 0x82, 0xcf, 0x8b, 0x28, 0x7f, 0x43, 0x62,
	0x56, 0x48, 0x54, 0x8f, 0x4a, 0xd4, 0xfe, 0x91, 0xa8, 0xef, 0x4b, 0x10, 0x02, 0x75, 0xaa, 0x66,
	0x3a, 0x68, 0x0c, 0x6a, 0xc3, 0x56, 0x62, 0xdf, 0xc3, 0x0f, 0xb8, 0x28, 0x79, 0xe9, 0xa5, 0x14,
	0x9a, 0x93, 0x1b, 0x68, 0x6a, 0x43, 0xcd, 0x4a, 0x5b, 0xa9, 0xce, 0x84, 0xb8, 0x51, 0xe9, 0xf1,
	0x8b, 0xa5, 0x91, 0x64, 0x3c, 0xd9, 0x7c, 0x41, 0xae, 0xa1, 0x63, 0x14, 0x15, 0x9a, 0xa2, 0xc9,
	0xa5, 0x28, 0x74, 0xdb, 0x7b, 0x34, 0x66, 0x93, 0x1f, 0x0f, 0xfc, 0x68, 0xbb, 0x0f, 0xf2, 0x00,
	0xfe, 0x6e, 0xe6, 0x24, 0xd8, 0x76, 0x2f, 0xaf, 0xa1, 0xd7, 0xdd, 0xe5, 0x72, 0xb5, 0xe6, 0xca,
	0xa5, 0x87, 0x15, 0xf2, 0x04, 0xed, 0x03, 0x71, 0x72, 0x75, 0xd0, 0xa2, 0x34, 0xe7, 0x5e, 0xff,
	0x48, 0xd5, 0x9d, 0x36, 0xac, 0x3c, 0xde, 0x41, 0x20, 0xd5, 0x6c, 0xfc, 0x4e, 0xa7, 0x2a, 0xc7,
	0x91, 0x66, 0x9f, 0xa3, 0x99, 0xdc, 0xfc, 0xf3, 0xd6, 0x3d, 0xa0, 0xb7, 0x8e, 0x4e, 0xdd, 0x55,
	0xba, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xea, 0xaa, 0x8d, 0x26, 0x64, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChaincodeClient is the client API for Chaincode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChaincodeClient interface {
	InstallCC(ctx context.Context, in *InstallCCRequest, opts ...grpc.CallOption) (*ServerStatus, error)
	InstantiateCC(ctx context.Context, in *InstantiateCCRequest, opts ...grpc.CallOption) (*InstantiateCCResponse, error)
}

type chaincodeClient struct {
	cc *grpc.ClientConn
}

func NewChaincodeClient(cc *grpc.ClientConn) ChaincodeClient {
	return &chaincodeClient{cc}
}

func (c *chaincodeClient) InstallCC(ctx context.Context, in *InstallCCRequest, opts ...grpc.CallOption) (*ServerStatus, error) {
	out := new(ServerStatus)
	err := c.cc.Invoke(ctx, "/protos.Chaincode/InstallCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaincodeClient) InstantiateCC(ctx context.Context, in *InstantiateCCRequest, opts ...grpc.CallOption) (*InstantiateCCResponse, error) {
	out := new(InstantiateCCResponse)
	err := c.cc.Invoke(ctx, "/protos.Chaincode/InstantiateCC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChaincodeServer is the server API for Chaincode service.
type ChaincodeServer interface {
	InstallCC(context.Context, *InstallCCRequest) (*ServerStatus, error)
	InstantiateCC(context.Context, *InstantiateCCRequest) (*InstantiateCCResponse, error)
}

func RegisterChaincodeServer(s *grpc.Server, srv ChaincodeServer) {
	s.RegisterService(&_Chaincode_serviceDesc, srv)
}

func _Chaincode_InstallCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallCCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaincodeServer).InstallCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Chaincode/InstallCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaincodeServer).InstallCC(ctx, req.(*InstallCCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chaincode_InstantiateCC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstantiateCCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaincodeServer).InstantiateCC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Chaincode/InstantiateCC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaincodeServer).InstantiateCC(ctx, req.(*InstantiateCCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chaincode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Chaincode",
	HandlerType: (*ChaincodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallCC",
			Handler:    _Chaincode_InstallCC_Handler,
		},
		{
			MethodName: "InstantiateCC",
			Handler:    _Chaincode_InstantiateCC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chaincode.proto",
}
