// Code generated by protoc-gen-go. DO NOT EDIT.
// source: channel.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateChannelRequest struct {
	ChannelId            string   `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChannelRequest) Reset()         { *m = CreateChannelRequest{} }
func (m *CreateChannelRequest) String() string { return proto.CompactTextString(m) }
func (*CreateChannelRequest) ProtoMessage()    {}
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8f385724121f37b, []int{0}
}

func (m *CreateChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChannelRequest.Unmarshal(m, b)
}
func (m *CreateChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChannelRequest.Marshal(b, m, deterministic)
}
func (m *CreateChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChannelRequest.Merge(m, src)
}
func (m *CreateChannelRequest) XXX_Size() int {
	return xxx_messageInfo_CreateChannelRequest.Size(m)
}
func (m *CreateChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChannelRequest proto.InternalMessageInfo

func (m *CreateChannelRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type CreateChannelResponse struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=protos.StatusCode" json:"status,omitempty"`
	TransactionId        string     `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateChannelResponse) Reset()         { *m = CreateChannelResponse{} }
func (m *CreateChannelResponse) String() string { return proto.CompactTextString(m) }
func (*CreateChannelResponse) ProtoMessage()    {}
func (*CreateChannelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8f385724121f37b, []int{1}
}

func (m *CreateChannelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChannelResponse.Unmarshal(m, b)
}
func (m *CreateChannelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChannelResponse.Marshal(b, m, deterministic)
}
func (m *CreateChannelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChannelResponse.Merge(m, src)
}
func (m *CreateChannelResponse) XXX_Size() int {
	return xxx_messageInfo_CreateChannelResponse.Size(m)
}
func (m *CreateChannelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChannelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChannelResponse proto.InternalMessageInfo

func (m *CreateChannelResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_SUCCESS
}

func (m *CreateChannelResponse) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

type JoinChannelRequest struct {
	ChannelId            string   `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinChannelRequest) Reset()         { *m = JoinChannelRequest{} }
func (m *JoinChannelRequest) String() string { return proto.CompactTextString(m) }
func (*JoinChannelRequest) ProtoMessage()    {}
func (*JoinChannelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8f385724121f37b, []int{2}
}

func (m *JoinChannelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinChannelRequest.Unmarshal(m, b)
}
func (m *JoinChannelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinChannelRequest.Marshal(b, m, deterministic)
}
func (m *JoinChannelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinChannelRequest.Merge(m, src)
}
func (m *JoinChannelRequest) XXX_Size() int {
	return xxx_messageInfo_JoinChannelRequest.Size(m)
}
func (m *JoinChannelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinChannelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinChannelRequest proto.InternalMessageInfo

func (m *JoinChannelRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateChannelRequest)(nil), "protos.CreateChannelRequest")
	proto.RegisterType((*CreateChannelResponse)(nil), "protos.CreateChannelResponse")
	proto.RegisterType((*JoinChannelRequest)(nil), "protos.JoinChannelRequest")
}

func init() { proto.RegisterFile("channel.proto", fileDescriptor_c8f385724121f37b) }

var fileDescriptor_c8f385724121f37b = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xbb, 0x1e, 0x2a, 0x1d, 0xdd, 0x1e, 0x86, 0x15, 0xca, 0x62, 0x41, 0x02, 0x82, 0x08,
	0x5d, 0xa5, 0xc5, 0x0f, 0xa0, 0x7b, 0xaa, 0x07, 0x0f, 0xeb, 0xcd, 0x8b, 0xa4, 0x9b, 0xb1, 0xae,
	0xda, 0x4c, 0xcd, 0xa4, 0x7e, 0x1a, 0x3f, 0xac, 0xb8, 0x49, 0xa5, 0xf5, 0xcf, 0xc1, 0x53, 0xe0,
	0x97, 0xf7, 0x78, 0xef, 0x25, 0x90, 0xd6, 0x8f, 0xda, 0x5a, 0x7a, 0x29, 0x96, 0x8e, 0x3d, 0x63,
	0xb7, 0x3d, 0x24, 0xdf, 0xaf, 0x79, 0xb1, 0x60, 0x1b, 0xa8, 0xba, 0x80, 0xac, 0x74, 0xa4, 0x3d,
	0x95, 0x41, 0x5c, 0xd1, 0xeb, 0x8a, 0xc4, 0xe3, 0x10, 0x20, 0xda, 0xef, 0x1b, 0x33, 0x48, 0x8e,
	0x92, 0x93, 0x5e, 0xd5, 0x8b, 0x64, 0x6a, 0xd4, 0x13, 0x1c, 0x7c, 0xb3, 0xc9, 0x92, 0xad, 0x10,
	0x9e, 0x42, 0x57, 0xbc, 0xf6, 0x2b, 0x69, 0x3d, 0xfd, 0x31, 0x86, 0x1c, 0x29, 0x6e, 0x5b, 0x5a,
	0xb2, 0xa1, 0x2a, 0x2a, 0xf0, 0x18, 0xfa, 0xde, 0x69, 0x2b, 0xba, 0xf6, 0x0d, 0xdb, 0xcf, 0x9c,
	0x9d, 0x36, 0x27, 0xdd, 0xa0, 0x53, 0xa3, 0x26, 0x80, 0xd7, 0xdc, 0xd8, 0x7f, 0x15, 0x1c, 0xbf,
	0x27, 0xb0, 0x1b, 0x1d, 0x78, 0x03, 0xe9, 0x56, 0x59, 0x3c, 0x5c, 0x97, 0xfa, 0x6d, 0x7a, 0x3e,
	0xfc, 0xe3, 0x36, 0x2c, 0x54, 0x1d, 0xbc, 0x84, 0xbd, 0x8d, 0x42, 0x98, 0xaf, 0xf5, 0x3f, 0x5b,
	0xe6, 0xd9, 0xd7, 0x7c, 0x72, 0x6f, 0xe4, 0xc2, 0x23, 0xa8, 0xce, 0xd5, 0x39, 0x0c, 0xd8, 0xcd,
	0x8b, 0x07, 0x3d, 0x73, 0x4d, 0x3d, 0x12, 0xf3, 0x3c, 0x9a, 0x73, 0x94, 0xde, 0x65, 0x5b, 0xf4,
	0x2c, 0xd0, 0x59, 0xf8, 0xbe, 0xc9, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x52, 0x2f, 0xbd,
	0xd6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChannelClient is the client API for Channel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChannelClient interface {
	CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*CreateChannelResponse, error)
	JoinChannel(ctx context.Context, in *JoinChannelRequest, opts ...grpc.CallOption) (*ServerStatus, error)
}

type channelClient struct {
	cc *grpc.ClientConn
}

func NewChannelClient(cc *grpc.ClientConn) ChannelClient {
	return &channelClient{cc}
}

func (c *channelClient) CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*CreateChannelResponse, error) {
	out := new(CreateChannelResponse)
	err := c.cc.Invoke(ctx, "/protos.Channel/CreateChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelClient) JoinChannel(ctx context.Context, in *JoinChannelRequest, opts ...grpc.CallOption) (*ServerStatus, error) {
	out := new(ServerStatus)
	err := c.cc.Invoke(ctx, "/protos.Channel/JoinChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelServer is the server API for Channel service.
type ChannelServer interface {
	CreateChannel(context.Context, *CreateChannelRequest) (*CreateChannelResponse, error)
	JoinChannel(context.Context, *JoinChannelRequest) (*ServerStatus, error)
}

// UnimplementedChannelServer can be embedded to have forward compatible implementations.
type UnimplementedChannelServer struct {
}

func (*UnimplementedChannelServer) CreateChannel(ctx context.Context, req *CreateChannelRequest) (*CreateChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChannel not implemented")
}
func (*UnimplementedChannelServer) JoinChannel(ctx context.Context, req *JoinChannelRequest) (*ServerStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinChannel not implemented")
}

func RegisterChannelServer(s *grpc.Server, srv ChannelServer) {
	s.RegisterService(&_Channel_serviceDesc, srv)
}

func _Channel_CreateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).CreateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Channel/CreateChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).CreateChannel(ctx, req.(*CreateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Channel_JoinChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServer).JoinChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Channel/JoinChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServer).JoinChannel(ctx, req.(*JoinChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Channel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Channel",
	HandlerType: (*ChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChannel",
			Handler:    _Channel_CreateChannel_Handler,
		},
		{
			MethodName: "JoinChannel",
			Handler:    _Channel_JoinChannel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "channel.proto",
}
