// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_SUCCESS StatusCode = 0
	StatusCode_FAILED  StatusCode = 1
)

var StatusCode_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILED",
}

var StatusCode_value = map[string]int32{
	"SUCCESS": 0,
	"FAILED":  1,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type ServerStatus struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=protos.StatusCode" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServerStatus) Reset()         { *m = ServerStatus{} }
func (m *ServerStatus) String() string { return proto.CompactTextString(m) }
func (*ServerStatus) ProtoMessage()    {}
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *ServerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStatus.Unmarshal(m, b)
}
func (m *ServerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStatus.Marshal(b, m, deterministic)
}
func (m *ServerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStatus.Merge(m, src)
}
func (m *ServerStatus) XXX_Size() int {
	return xxx_messageInfo_ServerStatus.Size(m)
}
func (m *ServerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStatus proto.InternalMessageInfo

func (m *ServerStatus) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_SUCCESS
}

func init() {
	proto.RegisterEnum("protos.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*ServerStatus)(nil), "protos.ServerStatus")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0x56, 0x5c,
	0x3c, 0xc1, 0xa9, 0x45, 0x65, 0xa9, 0x45, 0xc1, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x42, 0x5a, 0x5c,
	0x6c, 0xc5, 0x60, 0x96, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x9f, 0x91, 0x10, 0x44, 0x7d, 0xb1, 0x1e,
	0x44, 0xde, 0x39, 0x3f, 0x25, 0x35, 0x08, 0xaa, 0x42, 0x4b, 0x95, 0x8b, 0x0b, 0x21, 0x2a, 0xc4,
	0xcd, 0xc5, 0x1e, 0x1c, 0xea, 0xec, 0xec, 0x1a, 0x1c, 0x2c, 0xc0, 0x20, 0xc4, 0xc5, 0xc5, 0xe6,
	0xe6, 0xe8, 0xe9, 0xe3, 0xea, 0x22, 0xc0, 0xe8, 0x64, 0xc0, 0x25, 0x91, 0x5f, 0x94, 0xae, 0x97,
	0x96, 0x98, 0x54, 0x94, 0x99, 0xac, 0x5b, 0x9c, 0x92, 0xad, 0x9b, 0x9e, 0x0f, 0x35, 0x35, 0x4a,
	0x04, 0x45, 0x54, 0x1f, 0x22, 0x9a, 0x04, 0x71, 0x9c, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x60,
	0x99, 0xcb, 0x38, 0xb3, 0x00, 0x00, 0x00,
}
