// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_SUCCESS                     StatusCode = 0
	StatusCode_FAILED                      StatusCode = 1
	StatusCode_FAILED_NEW_CLIENT           StatusCode = 2
	StatusCode_FAILED_NEW_MSP_CLIENT       StatusCode = 3
	StatusCode_FAILED_GET_SIGNING_IDENTITY StatusCode = 4
	StatusCode_FAILED_CREATE_CHANNEL       StatusCode = 5
	StatusCode_FAILED_JOIN_CHANNEL         StatusCode = 6
)

var StatusCode_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILED",
	2: "FAILED_NEW_CLIENT",
	3: "FAILED_NEW_MSP_CLIENT",
	4: "FAILED_GET_SIGNING_IDENTITY",
	5: "FAILED_CREATE_CHANNEL",
	6: "FAILED_JOIN_CHANNEL",
}

var StatusCode_value = map[string]int32{
	"SUCCESS":                     0,
	"FAILED":                      1,
	"FAILED_NEW_CLIENT":           2,
	"FAILED_NEW_MSP_CLIENT":       3,
	"FAILED_GET_SIGNING_IDENTITY": 4,
	"FAILED_CREATE_CHANNEL":       5,
	"FAILED_JOIN_CHANNEL":         6,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type ServerStatus struct {
	Status               StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=protos.StatusCode" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServerStatus) Reset()         { *m = ServerStatus{} }
func (m *ServerStatus) String() string { return proto.CompactTextString(m) }
func (*ServerStatus) ProtoMessage()    {}
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *ServerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStatus.Unmarshal(m, b)
}
func (m *ServerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStatus.Marshal(b, m, deterministic)
}
func (m *ServerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStatus.Merge(m, src)
}
func (m *ServerStatus) XXX_Size() int {
	return xxx_messageInfo_ServerStatus.Size(m)
}
func (m *ServerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStatus proto.InternalMessageInfo

func (m *ServerStatus) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_SUCCESS
}

func init() {
	proto.RegisterEnum("protos.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*ServerStatus)(nil), "protos.ServerStatus")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0x56, 0x5c,
	0x3c, 0xc1, 0xa9, 0x45, 0x65, 0xa9, 0x45, 0xc1, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x42, 0x5a, 0x5c,
	0x6c, 0xc5, 0x60, 0x96, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x9f, 0x91, 0x10, 0x44, 0x7d, 0xb1, 0x1e,
	0x44, 0xde, 0x39, 0x3f, 0x25, 0x35, 0x08, 0xaa, 0x42, 0x6b, 0x0d, 0x23, 0x17, 0x17, 0x42, 0x58,
	0x88, 0x9b, 0x8b, 0x3d, 0x38, 0xd4, 0xd9, 0xd9, 0x35, 0x38, 0x58, 0x80, 0x41, 0x88, 0x8b, 0x8b,
	0xcd, 0xcd, 0xd1, 0xd3, 0xc7, 0xd5, 0x45, 0x80, 0x51, 0x48, 0x94, 0x4b, 0x10, 0xc2, 0x8e, 0xf7,
	0x73, 0x0d, 0x8f, 0x77, 0xf6, 0xf1, 0x74, 0xf5, 0x0b, 0x11, 0x60, 0x12, 0x92, 0xe4, 0x12, 0x45,
	0x12, 0xf6, 0x0d, 0x0e, 0x80, 0x49, 0x31, 0x0b, 0xc9, 0x73, 0x49, 0x43, 0xa5, 0xdc, 0x5d, 0x43,
	0xe2, 0x83, 0x3d, 0xdd, 0xfd, 0x3c, 0xfd, 0xdc, 0xe3, 0x3d, 0x5d, 0x5c, 0xfd, 0x42, 0x3c, 0x43,
	0x22, 0x05, 0x58, 0x90, 0xf4, 0x3a, 0x07, 0xb9, 0x3a, 0x86, 0xb8, 0xc6, 0x3b, 0x7b, 0x38, 0xfa,
	0xf9, 0xb9, 0xfa, 0x08, 0xb0, 0x0a, 0x89, 0x73, 0x09, 0x43, 0xa5, 0xbc, 0xfc, 0x3d, 0xfd, 0xe0,
	0x12, 0x6c, 0x4e, 0x06, 0x5c, 0x12, 0xf9, 0x45, 0xe9, 0x7a, 0x69, 0x89, 0x49, 0x45, 0x99, 0xc9,
	0xba, 0xc5, 0x29, 0xd9, 0xba, 0xe9, 0xf9, 0x50, 0xdf, 0x45, 0x89, 0xa0, 0x88, 0xea, 0x43, 0x44,
	0x93, 0x20, 0x81, 0x64, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x44, 0xc7, 0x9f, 0x3b, 0x01,
	0x00, 0x00,
}
